# Generated by Django 5.0 on 2023-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novapp', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
